{% set name = "requirements-detector" %}
{% set version = "1.4.0" %}
{% set sha256 = "0326c39269d87504c0e1b75932b86a6fdaa8a9eb3ce82243e5a21b696c2ade76" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/requirements_detector-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core

  run:
    - python >={{ python_min }},<4
    - astroid >=3.0.0
    - packaging >=21.3
    - semver >=3.0.0
    - tomli >=2.2.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - requirements_detector

about:
  home: https://github.com/landscapeio/requirements-detector
  license: MIT
  license_file: LICENSE
  summary: Python tool to find and list requirements of a Python project

extra:
  recipe-maintainers:
    - jakirkham
    - valeriupredoi
    - zklaus
