{% set name = "requirements-detector" %}
{% set version = "1.5.0" %}
{% set sha256 = "49ae15a73c1ab4e33c81e02166248d61323d331999c798b226bc21a09846dbbe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/requirements_detector-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core

  run:
    - python >={{ python_min }},<4
    - astroid >=3.0.0
    - packaging >=21.3
    - semver >=3.0.0
    - tomli >=2.2.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - requirements_detector

about:
  home: https://github.com/landscapeio/requirements-detector
  license: MIT
  license_file: LICENSE
  summary: Python tool to find and list requirements of a Python project

extra:
  recipe-maintainers:
    - jakirkham
    - valeriupredoi
    - zklaus
